#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/launch_app
- name: Run API
  community.docker.docker_container:
      name: simple-api
      image: "damaaax/tp-devops-simple-api:{{ version }}"
      networks:
          - name: "{{ network }}"
      env:
          DATABASE_HOST: "{{ DATABASE_HOST }}"
          DATABASE_PASSWORD: "{{ DATABASE_PASSWORD }}"
      pull: "always"

- name: Run FRONTEND
  community.docker.docker_container:
    name: simple-frontend
    image: "damaaax/tp-devops-simple-frontend:{{ version }}"
    networks:
        - name: "{{ network }}"
    pull: "always"
    restart: true
