- hosts: all
  gather_facts: false
  become: true
  vars:
      version: latest
      network: app-network
  roles:
      - docker
      - create_network
      - launch_database
      - launch_app
      - launch_proxy
